export const FETCH_PROFILE_SUCCESSFUL = 'FETCH_PROFILE_SUCCESSFUL';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const CREATE_PROFILE_SUCCESSFUL = 'CREATE_PROFILE_SUCCESSFUL';
export const CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE';

export const UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
