export const FETCH_PAGE_SUCCESSFUL = 'FETCH_PAGE_SUCCESSFUL';
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE';

export const FETCH_RECENT_SUCCESSFUL = 'FETCH_PAGES_SUCCESSFUL';
export const FETCH_RECENT_FAILURE = 'FETCH_PAGES_FAILURE';

export const CREATE_PAGE_SUCCESSFUL = 'CREATE_PAGE_SUCCESSFUL';
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE';

export const UPDATE_PAGE_SUCCESSFUL = 'UPDATE_PAGE_SUCCESSFUL';
export const UPDATE_PAGE_FAILURE = 'UPDATE_PAGE_FAILURE';

export const DELETE_PAGE_SUCCESSFUL = 'DELETE_PAGE_SUCCESSFUL';
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE';
